# Site settings
title:          Блог Ивана Гаврилина
description:    "Сторителлинг о психологии, отношения и смысле жизни"
# baseurl:        "/tale"
url:            "https://ivangavrilin.ru"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Иван Гаврилин
  url:          https://ivangavrilin.ru
  email:        gavrilinivan@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# /:year-:month-:day
