# Site settings
title:          Блог Ивана Гаврилина
description:    "Рассказы о психологии, отношениях и смысле жизни"
baseurl:        ""
url:            "https://ivangavrilin.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Иван Гаврилин
  url:          https://ivangavrilin.github.io
  email:        gvrilinivan@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
