# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Блог Ивана Гаврилина
tagline:             'Сторителлинг и психология'
description:         'Блог Ивана Гаврилина: сторителлинг, циник, джокер'
url:                 https://ivangavrilin.ru
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Иван Гаврилин
  url:               https://ivangavrilin.ru
  email:             gavrilinivan@gmail.com

# Custom vars
version:             1.0.0
